<?php

namespace App\Support;

use App\Models\Payment;
use App\Models\Subscription;

/**
 * The fields the client renders into the WhatsApp message templates
 * ({{start_date}}, {{amount_paid}}, {{barcode_url}}, ...).
 *
 * Shared by two callers on purpose. OperationalNotifier stamps these onto a
 * notification when it is created, and NotificationController refreshes them
 * when the list is read — a stored payload is a snapshot, and the attendance
 * code in particular is regenerated by migration, so a frozen one would hand a
 * member a barcode that no longer scans.
 */
final class SubscriptionMessagePayload
{
    /** Relations the payload reads; eager-load these to avoid N+1. */
    public const RELATIONS = ['member:id,name,phone,attendance_code', 'plan:id,name', 'payments'];

    /**
     * @return array<string, mixed>
     */
    public static function for(Subscription $subscription): array
    {
        $code = $subscription->member?->attendance_code;

        return [
            'subscription_id' => $subscription->id,
            'member_id' => $subscription->member_id,
            'member_name' => $subscription->member?->name,
            'member_phone' => $subscription->member?->phone,
            'attendance_code' => $code,
            'attendance_qr' => $code ? AttendanceCode::payload('member', $code) : null,
            'plan_name' => $subscription->plan?->name,
            'start_date' => $subscription->start_date?->toDateString(),
            'end_date' => $subscription->end_date?->toDateString(),
            'amount_paid' => self::paidTotal($subscription),
            'sessions_remaining' => $subscription->sessions_remaining,
        ];
    }

    /**
     * Net collected amount (refund rows store negative amounts), mirroring
     * SubscriptionResource::paidTotal().
     */
    private static function paidTotal(Subscription $subscription): string
    {
        return $subscription->payments
            ->filter(fn ($payment): bool => in_array($payment->status, Payment::SETTLEMENT_STATUSES, true))
            ->reduce(
                fn (string $carry, $payment): string => bcadd($carry, (string) $payment->amount, 2),
                '0.00',
            );
    }
}
