<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

/**
 * Seed membership + offer plans covering every product-rule case the app supports.
 *
 * Dimensions covered:
 * - type: membership | offer
 * - category: gym_access | personal_training | classes | nutrition | recovery
 * - sessions: unlimited | limited packs
 * - duration: day pass, weeks, months (1/2/3/6/12), days-only edge cases
 * - sellability: active forever, active window, inactive, expired offer, upcoming offer
 * - access window: all-day, morning, daytime, evening, overnight
 * - freeze policy: none, free freeze, approval required, min/max combos
 * - grace: access_grace_days + cancellation_grace_days (0 … generous)
 * - commission_rate: zero / low / mid / high
 * - price: free trial, budget, standard, premium, VIP
 *
 * Idempotent via updateOrCreate on name.
 */
class PlanSeeder extends Seeder
{
    public function run(): void
    {
        $today = Carbon::today();

        foreach ($this->plans($today) as $plan) {
            Plan::query()->updateOrCreate(
                ['name' => $plan['name']],
                $plan,
            );
        }
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function plans(Carbon $today): array
    {
        return [
            // ── Core unlimited memberships (gym_access) ──────────────────────
            $this->plan([
                'name' => 'Day Pass',
                'description' => 'Single-day unlimited gym floor access. No freeze or grace.',
                'price' => 100.00,
                'duration_days' => 1,
                'duration_months' => null,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'access_grace_days' => 0,
                'cancellation_grace_days' => 0,
                'commission_rate' => 0.0000,
            ]),
            $this->plan([
                'name' => 'Weekly Trial',
                'description' => '7-day unlimited access for first-time visitors.',
                'price' => 250.00,
                'duration_days' => 7,
                'duration_months' => null,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'access_grace_days' => 1,
                'cancellation_grace_days' => 1,
                'commission_rate' => 0.0300,
            ]),
            $this->plan([
                'name' => 'Monthly Gym Access',
                'description' => 'Standard unlimited gym access for one calendar month.',
                'price' => 650.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 5,
                'min_freeze_days' => 1,
                'access_grace_days' => 3,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.0800,
            ]),
            $this->plan([
                'name' => 'Premium Monthly',
                'description' => 'Unlimited access with premium floor privileges for one month.',
                'price' => 950.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 7,
                'min_freeze_days' => 1,
                'access_grace_days' => 3,
                'cancellation_grace_days' => 3,
                'commission_rate' => 0.1000,
            ]),
            $this->plan([
                'name' => 'Two Month Starter',
                'description' => 'Two months of unlimited access for new members.',
                'price' => 1200.00,
                'duration_days' => 60,
                'duration_months' => 2,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 8,
                'min_freeze_days' => 1,
                'access_grace_days' => 3,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.0800,
            ]),
            $this->plan([
                'name' => 'Quarterly Transformation',
                'description' => 'Three months unlimited access; freezes need admin approval.',
                'price' => 3600.00,
                'duration_days' => 90,
                'duration_months' => 3,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 14,
                'min_freeze_days' => 3,
                'freeze_requires_approval' => true,
                'access_grace_days' => 5,
                'cancellation_grace_days' => 3,
                'commission_rate' => 0.1200,
            ]),
            $this->plan([
                'name' => 'Six Month Commitment',
                'description' => 'Half-year unlimited membership with extended freeze allowance.',
                'price' => 6500.00,
                'duration_days' => 180,
                'duration_months' => 6,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 21,
                'min_freeze_days' => 3,
                'freeze_requires_approval' => true,
                'access_grace_days' => 7,
                'cancellation_grace_days' => 5,
                'commission_rate' => 0.1300,
            ]),
            $this->plan([
                'name' => 'Yearly VIP',
                'description' => 'Annual unlimited membership with VIP freeze and grace rules.',
                'price' => 10500.00,
                'duration_days' => 365,
                'duration_months' => 12,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 30,
                'min_freeze_days' => 7,
                'freeze_requires_approval' => true,
                'access_grace_days' => 7,
                'cancellation_grace_days' => 7,
                'commission_rate' => 0.1500,
            ]),
            $this->plan([
                'name' => 'Corporate Plan',
                'description' => 'Corporate partner rate — unlimited floor access for one month.',
                'price' => 950.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 5,
                'min_freeze_days' => 1,
                'access_grace_days' => 3,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.1000,
            ]),

            // ── Free / zero-commission edge ───────────────────────────────────
            $this->plan([
                'name' => 'Free Guest Pass',
                'description' => 'Complimentary one-day pass (price 0). Covers free-plan + zero commission.',
                'price' => 0.00,
                'duration_days' => 1,
                'duration_months' => null,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'access_grace_days' => 0,
                'cancellation_grace_days' => 0,
                'commission_rate' => 0.0000,
            ]),

            // ── Time-windowed access (same-day windows) ───────────────────────
            $this->plan([
                'name' => 'Morning Access Monthly',
                'description' => 'Unlimited access only 06:00–12:00 for one month.',
                'price' => 480.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'access_starts_at' => '06:00',
                'access_ends_at' => '12:00',
                'max_freeze_days' => 3,
                'min_freeze_days' => 1,
                'access_grace_days' => 2,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.0600,
            ]),
            $this->plan([
                'name' => 'Daytime Access Monthly',
                'description' => 'Unlimited access only 09:00–17:00 for one month.',
                'price' => 520.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'access_starts_at' => '09:00',
                'access_ends_at' => '17:00',
                'max_freeze_days' => 3,
                'min_freeze_days' => 1,
                'access_grace_days' => 2,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.0600,
            ]),
            $this->plan([
                'name' => 'Evening Access Monthly',
                'description' => 'Unlimited access only 16:00–23:00 for one month.',
                'price' => 550.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'access_starts_at' => '16:00',
                'access_ends_at' => '23:00',
                'max_freeze_days' => 3,
                'min_freeze_days' => 1,
                'access_grace_days' => 2,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.0700,
            ]),

            // ── Overnight access window (crosses midnight) ────────────────────
            $this->plan([
                'name' => 'Night Owl Access',
                'description' => 'Overnight window 22:00–06:00 (crosses midnight). Unlimited sessions.',
                'price' => 400.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'access_starts_at' => '22:00',
                'access_ends_at' => '06:00',
                'max_freeze_days' => 2,
                'min_freeze_days' => 1,
                'access_grace_days' => 1,
                'cancellation_grace_days' => 1,
                'commission_rate' => 0.0500,
            ]),

            // ── Fitness Studio Standalone Plans (Jiu-Jitsu & Classes - No Gym Access) ──
            $this->plan([
                'name' => 'Jiu-Jitsu Studio Monthly',
                'description' => '12 Jiu-Jitsu martial arts sessions over one month. Standalone studio access.',
                'price' => 1800.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'sessions_count' => 12,
                'is_unlimited_sessions' => false,
                'type' => 'fitness_studio',
                'category' => 'fitness_studio',
                'max_freeze_days' => 5,
                'min_freeze_days' => 1,
                'access_grace_days' => 2,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.1000,
            ]),
            $this->plan([
                'name' => 'Karate Studio Membership',
                'description' => '8 Karate training sessions over one month. Standalone studio plan.',
                'price' => 1500.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'sessions_count' => 8,
                'is_unlimited_sessions' => false,
                'type' => 'fitness_studio',
                'category' => 'fitness_studio',
                'max_freeze_days' => 5,
                'min_freeze_days' => 1,
                'access_grace_days' => 2,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.1000,
            ]),
            $this->plan([
                'name' => 'CrossFit Studio Unlimited',
                'description' => 'Unlimited CrossFit studio class access for one month.',
                'price' => 2200.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'sessions_count' => null,
                'is_unlimited_sessions' => true,
                'type' => 'fitness_studio',
                'category' => 'fitness_studio',
                'max_freeze_days' => 7,
                'min_freeze_days' => 1,
                'access_grace_days' => 3,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.1200,
            ]),

            // ── Session-capped memberships (classes) ──────────────────────────
            $this->plan([
                'name' => 'Classes Monthly',
                'description' => '16 bookable class sessions over one month.',
                'price' => 800.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'sessions_count' => 16,
                'is_unlimited_sessions' => false,
                'type' => 'membership',
                'category' => 'classes',
                'max_freeze_days' => 5,
                'min_freeze_days' => 1,
                'access_grace_days' => 2,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.0900,
            ]),
            $this->plan([
                'name' => 'Classes Quarterly Pack',
                'description' => '48 class sessions over three months; freezes need approval.',
                'price' => 2100.00,
                'duration_days' => 90,
                'duration_months' => 3,
                'sessions_count' => 48,
                'is_unlimited_sessions' => false,
                'type' => 'membership',
                'category' => 'classes',
                'max_freeze_days' => 10,
                'min_freeze_days' => 2,
                'freeze_requires_approval' => true,
                'access_grace_days' => 3,
                'cancellation_grace_days' => 3,
                'commission_rate' => 0.1000,
            ]),
            $this->plan([
                'name' => 'Single Class Drop-in',
                'description' => 'One class session valid for 7 days.',
                'price' => 120.00,
                'duration_days' => 7,
                'duration_months' => null,
                'sessions_count' => 1,
                'is_unlimited_sessions' => false,
                'type' => 'membership',
                'category' => 'classes',
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'access_grace_days' => 0,
                'cancellation_grace_days' => 0,
                'commission_rate' => 0.0500,
            ]),

            // ── Personal training packs ───────────────────────────────────────
            $this->plan([
                'name' => '4 Personal Training Sessions',
                'description' => 'Starter PT pack: 4 sessions within 30 days.',
                'price' => 1000.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'sessions_count' => 4,
                'is_unlimited_sessions' => false,
                'type' => 'membership',
                'category' => 'personal_training',
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'access_grace_days' => 0,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.1000,
            ]),
            $this->plan([
                'name' => '8 Personal Training Sessions',
                'description' => 'Standard PT pack: 8 sessions within 30 days.',
                'price' => 1800.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'sessions_count' => 8,
                'is_unlimited_sessions' => false,
                'type' => 'membership',
                'category' => 'personal_training',
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'access_grace_days' => 0,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.1200,
            ]),
            $this->plan([
                'name' => '12 Personal Training Sessions',
                'description' => 'PT pack: 12 sessions over 45 days (days-only duration, no months).',
                'price' => 2500.00,
                'duration_days' => 45,
                'duration_months' => null,
                'sessions_count' => 12,
                'is_unlimited_sessions' => false,
                'type' => 'membership',
                'category' => 'personal_training',
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'access_grace_days' => 0,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.1400,
            ]),
            $this->plan([
                'name' => '24 Personal Training Sessions',
                'description' => 'Heavy PT commitment: 24 sessions over 3 months with freeze approval.',
                'price' => 4800.00,
                'duration_days' => 90,
                'duration_months' => 3,
                'sessions_count' => 24,
                'is_unlimited_sessions' => false,
                'type' => 'membership',
                'category' => 'personal_training',
                'max_freeze_days' => 7,
                'min_freeze_days' => 2,
                'freeze_requires_approval' => true,
                'access_grace_days' => 2,
                'cancellation_grace_days' => 3,
                'commission_rate' => 0.1500,
            ]),

            // ── Nutrition ─────────────────────────────────────────────────────
            $this->plan([
                'name' => 'Nutrition Follow-up Monthly',
                'description' => '4 nutrition consults over one month (add-on style membership).',
                'price' => 900.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'sessions_count' => 4,
                'is_unlimited_sessions' => false,
                'type' => 'membership',
                'category' => 'nutrition',
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'access_grace_days' => 0,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.1000,
            ]),
            $this->plan([
                'name' => 'Nutrition Full Program',
                'description' => '12 nutrition sessions over 90 days with freeze approval.',
                'price' => 2400.00,
                'duration_days' => 90,
                'duration_months' => 3,
                'sessions_count' => 12,
                'is_unlimited_sessions' => false,
                'type' => 'membership',
                'category' => 'nutrition',
                'max_freeze_days' => 7,
                'min_freeze_days' => 1,
                'freeze_requires_approval' => true,
                'access_grace_days' => 2,
                'cancellation_grace_days' => 3,
                'commission_rate' => 0.1100,
            ]),

            // ── Recovery ──────────────────────────────────────────────────────
            $this->plan([
                'name' => 'Recovery Massage Package',
                'description' => '6 recovery / mobility sessions over 30 days.',
                'price' => 1400.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'sessions_count' => 6,
                'is_unlimited_sessions' => false,
                'type' => 'membership',
                'category' => 'recovery',
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'access_grace_days' => 0,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.1000,
            ]),
            $this->plan([
                'name' => 'Unlimited Recovery Month',
                'description' => 'Unlimited recovery suite access for one month (unlimited + recovery category).',
                'price' => 2200.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'is_unlimited_sessions' => true,
                'type' => 'membership',
                'category' => 'recovery',
                'max_freeze_days' => 3,
                'min_freeze_days' => 1,
                'access_grace_days' => 2,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.0900,
            ]),

            // ── Active offers (time-boxed sell window) ─────────────────────────
            $this->plan([
                'name' => 'Student Off-Peak',
                'description' => 'Active offer: discounted off-peak 07:00–16:00 access for students.',
                'price' => 420.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'offer',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'valid_from' => $today->copy()->subDays(15)->toDateString(),
                'valid_to' => $today->copy()->addDays(45)->toDateString(),
                'access_starts_at' => '07:00',
                'access_ends_at' => '16:00',
                'max_freeze_days' => 3,
                'min_freeze_days' => 1,
                'access_grace_days' => 2,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.0500,
            ]),
            $this->plan([
                'name' => 'Weekend Warrior',
                'description' => 'Active offer: Friday–Sunday focused monthly access (all-day window).',
                'price' => 520.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'offer',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'valid_from' => $today->copy()->subDays(10)->toDateString(),
                'valid_to' => $today->copy()->addDays(50)->toDateString(),
                'max_freeze_days' => 2,
                'min_freeze_days' => 1,
                'access_grace_days' => 1,
                'cancellation_grace_days' => 1,
                'commission_rate' => 0.0500,
            ]),
            $this->plan([
                'name' => 'Summer PT Promo 8 Sessions',
                'description' => 'Active seasonal offer: 8 PT sessions at promo price.',
                'price' => 1500.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'sessions_count' => 8,
                'is_unlimited_sessions' => false,
                'type' => 'offer',
                'category' => 'personal_training',
                'valid_from' => $today->copy()->subDays(5)->toDateString(),
                'valid_to' => $today->copy()->addDays(60)->toDateString(),
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'access_grace_days' => 0,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.1300,
            ]),
            $this->plan([
                'name' => 'Ramadan Classes Bundle',
                'description' => 'Active offer: 12 evening classes for the season.',
                'price' => 700.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'sessions_count' => 12,
                'is_unlimited_sessions' => false,
                'type' => 'offer',
                'category' => 'classes',
                'valid_from' => $today->copy()->subDays(3)->toDateString(),
                'valid_to' => $today->copy()->addDays(40)->toDateString(),
                'access_starts_at' => '18:00',
                'access_ends_at' => '23:30',
                'max_freeze_days' => 2,
                'min_freeze_days' => 1,
                'access_grace_days' => 1,
                'cancellation_grace_days' => 1,
                'commission_rate' => 0.0800,
            ]),
            $this->plan([
                'name' => 'Nutrition Kickstart Offer',
                'description' => 'Active offer: 6 nutrition sessions for new members.',
                'price' => 1100.00,
                'duration_days' => 45,
                'duration_months' => null,
                'sessions_count' => 6,
                'is_unlimited_sessions' => false,
                'type' => 'offer',
                'category' => 'nutrition',
                'valid_from' => $today->copy()->subDays(7)->toDateString(),
                'valid_to' => $today->copy()->addDays(30)->toDateString(),
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'access_grace_days' => 0,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.1000,
            ]),
            $this->plan([
                'name' => 'Recovery Intro Offer',
                'description' => 'Active offer: 3 recovery sessions intro pack.',
                'price' => 650.00,
                'duration_days' => 21,
                'duration_months' => null,
                'sessions_count' => 3,
                'is_unlimited_sessions' => false,
                'type' => 'offer',
                'category' => 'recovery',
                'valid_from' => $today->copy()->subDays(2)->toDateString(),
                'valid_to' => $today->copy()->addDays(28)->toDateString(),
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'access_grace_days' => 0,
                'cancellation_grace_days' => 1,
                'commission_rate' => 0.0900,
            ]),

            // ── Sellability edge cases ────────────────────────────────────────
            $this->plan([
                'name' => 'Inactive Legacy Membership',
                'description' => 'Inactive membership — not sellable (is_active=false).',
                'price' => 500.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'is_active' => false,
                'max_freeze_days' => 5,
                'min_freeze_days' => 1,
                'access_grace_days' => 2,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.0500,
            ]),
            $this->plan([
                'name' => 'Expired Promo Offer',
                'description' => 'Offer whose valid_to is in the past — active flag true but not sellable.',
                'price' => 350.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'offer',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'is_active' => true,
                'valid_from' => $today->copy()->subDays(90)->toDateString(),
                'valid_to' => $today->copy()->subDays(1)->toDateString(),
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'access_grace_days' => 0,
                'cancellation_grace_days' => 0,
                'commission_rate' => 0.0400,
            ]),
            $this->plan([
                'name' => 'Upcoming Launch Offer',
                'description' => 'Offer that starts in the future — not sellable yet.',
                'price' => 399.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'offer',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'is_active' => true,
                'valid_from' => $today->copy()->addDays(14)->toDateString(),
                'valid_to' => $today->copy()->addDays(60)->toDateString(),
                'max_freeze_days' => 2,
                'min_freeze_days' => 1,
                'access_grace_days' => 1,
                'cancellation_grace_days' => 1,
                'commission_rate' => 0.0500,
            ]),
            $this->plan([
                'name' => 'Inactive Expired PT Offer',
                'description' => 'Double-negative case: inactive + expired window + limited sessions.',
                'price' => 999.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'sessions_count' => 6,
                'is_unlimited_sessions' => false,
                'type' => 'offer',
                'category' => 'personal_training',
                'is_active' => false,
                'valid_from' => $today->copy()->subDays(120)->toDateString(),
                'valid_to' => $today->copy()->subDays(30)->toDateString(),
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'access_grace_days' => 0,
                'cancellation_grace_days' => 0,
                'commission_rate' => 0.0000,
            ]),

            // ── Policy extremes ───────────────────────────────────────────────
            $this->plan([
                'name' => 'Strict No-Grace Membership',
                'description' => 'No freeze, no access grace, no cancellation grace — strictest rules.',
                'price' => 700.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'freeze_requires_approval' => false,
                'access_grace_days' => 0,
                'cancellation_grace_days' => 0,
                'commission_rate' => 0.0700,
            ]),
            $this->plan([
                'name' => 'Flexible Freeze Membership',
                'description' => 'High freeze allowance without approval — tests free-form freezes.',
                'price' => 1100.00,
                'duration_days' => 60,
                'duration_months' => 2,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 20,
                'min_freeze_days' => 1,
                'freeze_requires_approval' => false,
                'access_grace_days' => 5,
                'cancellation_grace_days' => 5,
                'commission_rate' => 0.0900,
            ]),
            $this->plan([
                'name' => 'Approval-Only Freeze Membership',
                'description' => 'Freezes allowed only with approval; min freeze equals max (single-length freezes).',
                'price' => 800.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 7,
                'min_freeze_days' => 7,
                'freeze_requires_approval' => true,
                'access_grace_days' => 3,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.0800,
            ]),
            $this->plan([
                'name' => 'Long Cancellation Grace Monthly',
                'description' => '14-day cancellation grace for refunds; otherwise standard monthly access.',
                'price' => 750.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 5,
                'min_freeze_days' => 1,
                'access_grace_days' => 3,
                'cancellation_grace_days' => 14,
                'commission_rate' => 0.0800,
            ]),
            $this->plan([
                'name' => 'High Commission VIP Month',
                'description' => 'Premium priced plan with high seller commission (15%).',
                'price' => 1500.00,
                'duration_days' => 30,
                'duration_months' => 1,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 10,
                'min_freeze_days' => 2,
                'freeze_requires_approval' => true,
                'access_grace_days' => 5,
                'cancellation_grace_days' => 5,
                'commission_rate' => 0.1500,
            ]),
            $this->plan([
                'name' => 'Days-Only 45 Day Access',
                'description' => 'Duration driven only by duration_days (duration_months null).',
                'price' => 900.00,
                'duration_days' => 45,
                'duration_months' => null,
                'type' => 'membership',
                'category' => 'gym_access',
                'is_unlimited_sessions' => true,
                'max_freeze_days' => 5,
                'min_freeze_days' => 1,
                'access_grace_days' => 3,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.0800,
            ]),
            $this->plan([
                'name' => 'Session Pack No Duration Months',
                'description' => 'Limited sessions + days-only duration (common PT/offer pattern).',
                'price' => 1600.00,
                'duration_days' => 40,
                'duration_months' => null,
                'sessions_count' => 10,
                'is_unlimited_sessions' => false,
                'type' => 'membership',
                'category' => 'personal_training',
                'max_freeze_days' => 0,
                'min_freeze_days' => 0,
                'access_grace_days' => 0,
                'cancellation_grace_days' => 2,
                'commission_rate' => 0.1100,
            ]),
        ];
    }

    /**
     * Merge explicit fields onto safe defaults so every plan has a full column set.
     *
     * @param  array<string, mixed>  $overrides
     * @return array<string, mixed>
     */
    private function plan(array $overrides): array
    {
        $isUnlimited = (bool) ($overrides['is_unlimited_sessions'] ?? true);

        $defaults = [
            'description' => null,
            'duration_months' => null,
            'sessions_count' => $isUnlimited ? null : 1,
            'is_unlimited_sessions' => $isUnlimited,
            'type' => 'membership',
            'category' => 'gym_access',
            'is_active' => true,
            'valid_from' => null,
            'valid_to' => null,
            'access_starts_at' => null,
            'access_ends_at' => null,
            'max_freeze_days' => 0,
            'access_grace_days' => 0,
            'cancellation_grace_days' => 2,
            'min_freeze_days' => 0,
            'freeze_requires_approval' => false,
            'commission_rate' => 0.0000,
        ];

        $plan = array_merge($defaults, $overrides);

        if ($plan['is_unlimited_sessions']) {
            $plan['sessions_count'] = null;
        }

        // Offers always need a validity window for StorePlanRequest parity.
        if ($plan['type'] === 'offer') {
            $plan['valid_from'] ??= now()->toDateString();
            $plan['valid_to'] ??= now()->addDays(30)->toDateString();
        }

        return $plan;
    }
}
